name: publish on github

on:
  push:
    branches:
      - main
      - chore/publish-package
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@langdb'

      - name: Create .npmrc
        run: |
              echo "@langdb:registry=https://npm.pkg.github.com" >> .npmrc
              echo "//npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> .npmrc      
      - run: npm install
      - run: npm run build
      - name: Prepare for version bump
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # Stage any changes, including potential changes from npm run build
          git add .
          # Generate a unique pre-release version with a timestamp
          # Example: 1.0.0-beta.0+20230915.123456
          VERSION=$(npm version prerelease --preid=beta.$(date +%Y%m%d.%H%M%S) --no-git-tag-version)
          echo "New version: $VERSION"
          node sync-version.js
          git add package.json package-lock.json

      
      - name: Commit and push changes
        run: |
            # Commit all staged changes, including the version bump
            git commit -m "chore(release): $(node -p "require('./package.json').version")" || echo "No changes to commit"
            # Create tag for the new version
            git tag v$(node -p "require('./package.json').version")
            git push --follow-tags
            cd dist && npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}